services:
  mysql:
    image: mysql:8.0
    container_name: nyonya_jumbo_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root        # Password root
      MYSQL_DATABASE: db_nyonya_jumbo        # Database otomatis dibuat saat init
      MYSQL_USER: unyonya          # User khusus (optional)
      MYSQL_PASSWORD: pwnyonya         # Password user (optional)
    volumes:
      - nyonya_jumbo_mysql_data:/var/lib/mysql
    # Opsional: Command ini untuk fix authentication method plugin error di beberapa client lama
    command: --default-authentication-plugin=mysql_native_password

volumes:
  nyonya_jumbo_mysql_data: 
    driver: local